server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker-logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: docker-logs
      __path__: /var/lib/docker/containers/*/*log

  pipeline_stages:

  - json:
      expressions:
        stream: stream
        attrs: attrs
        tag: attrs.tag
        log: log

  - regex:
      expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
      source: "tag"

  - json:
      source: log
      expressions:
        event: message.event
        method: message.method
        path: message.path
        query: message.query
        client_ip: message.client_ip
        request_id: message.request_id
        level: level
        logger: name
        status_code: message.status_code
        process_time: message.process_time
        exception: message.exception


  - labels:
      tag:
      image_name:
      container_name:
      event:
      method:
      path:
      query:
      client_ip:
      request_id:
      level:
      logger:
      status_code:
      process_time:
      exception:
